sonar.projectKey=generic-project
sonar.projectName=Generic Project
sonar.sources=.
sonar.exclusions=**/.git/**,**/.harness/**,**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
sonar.sourceEncoding=UTF-8
